trigger:
  branches:
    include:
      - main
  paths:
    include:
      - AirIndia/*
      - CTC/*
pool:
  vmImage: 'windows-latest'

steps:
  - checkout: self
    fetchDepth: 0

  - task: UseJava@1
    inputs:
      versionSpec: '1.8'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - powershell: |
      Write-Host "Detecting changed Java files..."
      $changes = git diff --name-only HEAD^ HEAD | Where-Object { $_ -like "*.java" }

      if (-not $changes) {
        Write-Host "No Java changes detected."
        Write-Host "##vso[task.setvariable variable=skipBuild]true"
        exit 0
      }

      Write-Host "Changed Java files:`n$changes"

      # Save as CSV for next step
      $csv = $changes -join ','
      Write-Host "##vso[task.setvariable variable=skipBuild]false"
      Write-Host "##vso[task.setvariable variable=javaFilesCsv]$csv"
    displayName: "Detect changed Java files"

  - powershell: |
      if ('$(skipBuild)' -eq 'true') {
        Write-Host "No Java changes, skipping."
        exit 0
      }

      $files = "$(javaFilesCsv)".Split(',') | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne '' }
      Write-Host "Java files to compile: $($files -join ', ')"

      foreach ($file in $files) {
        Write-Host "Compiling $file ..."

        $module = ($file -replace '\\','/') -split '/' | Select-Object -First 1
        $outputDir = "$module/target/classes"

        New-Item -ItemType Directory -Force -Path $outputDir | Out-Null

        # Compile just this file, outputting to classes folder
        & javac -d $outputDir $file
        if ($LASTEXITCODE -ne 0) {
          throw "Compilation failed for $file"
        }
      }

      Write-Host "Compilation finished."
    displayName: "Compile changed Java files"
    condition: ne(variables['skipBuild'], 'true')

  - task: PublishBuildArtifacts@1
    displayName: "Publish compiled classes"
    inputs:
      pathtoPublish: '$(Build.SourcesDirectory)/*/target/classes'
      artifactName: 'classes'
    condition: ne(variables['skipBuild'], 'true')
