trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  PEGA_BASE_URL: 'https://pega.example.com/prweb'
  CLIENT_ID: '$(PEGA_CLIENT_ID)'
  CLIENT_SECRET: '$(PEGA_CLIENT_SECRET)'
  USERNAME: '$(PEGA_USERNAME)'
  PASSWORD: '$(PEGA_PASSWORD)'
  SOURCE_PIPELINE_ID: '1234'

steps:
- task: Bash@3
  displayName: 'Get OAuth Token'
  inputs:
    targetType: 'inline'
    script: |
      echo "Getting OAuth token..."
      ACCESS_TOKEN=$(curl -s -X POST \
        "$PEGA_BASE_URL/PRRestService/oauth2/v1/token" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "grant_type=password" \
        -d "client_id=$CLIENT_ID" \
        -d "client_secret=$CLIENT_SECRET" \
        -d "username=$USERNAME" \
        -d "password=$PASSWORD" | jq -r '.access_token')
      echo "##vso[task.setvariable variable=ACCESS_TOKEN]$ACCESS_TOKEN"

- task: Bash@3
  displayName: 'List Pipelines'
  inputs:
    targetType: 'inline'
    script: |
      echo "Listing pipelines..."
      curl -X GET "$PEGA_BASE_URL/prweb/api/v1/pipelines" \
        -H "Accept: application/json" \
        -H "Authorization: Bearer $(ACCESS_TOKEN)"
